# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: affc3e41d1594ba49cefffcd0b5ff8ecab62a6271ac2e530cdc46d827aae0619a27b198aa6910cdb9721b41eabd17c13f20a74fa5faf9c481836f815a86b3be6

test:
  secret_key_base: 5042fc50c5cebcb154a641d982452091ab253fb9ce756c1b32a0118573155fc413577f0f2dcfddb4bfcbc78b6e731a5c01de01c16a8dd44c5948362e3de1336f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
